name: Build UACMe

on:
  # Дозволяє запускати цей процес вручну з вкладки Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Крок 1: Завантаження коду
      - name: Checkout repository
        uses: actions/checkout@v4

      # Крок 2: Налаштування середовища компілятора
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      # Крок 3: Компіляція всього рішення
      - name: Build Solution
        working-directory: ./Source
        run: MSBuild.exe UACMe.sln /p:Configuration=Release /p:Platform=x64

      # Крок 4: Створення "сцени" для артефактів і копіювання файлів (НОВИЙ НАДІЙНИЙ КРОК)
      - name: Create Staging Directory and Gather Files
        run: |
          mkdir staging
          copy Source\Akagi\output\x64\Release\akagi64.exe staging\
          copy Source\Akatsuki\output\x64\Release\Akatsuki64.dll staging\
          copy Source\Fubuki\output\x64\Release\Fubuki64.dll staging\
          echo "--- Staging Directory Contents ---"
          dir staging

      # Крок 5: Пакування папки "staging" в артефакт
      - name: Upload Artifact Package
        uses: actions/upload-artifact@v4
        with:
          name: UACMe-Package-x64
          path: staging/
