name: Build UACMe

on:
  # Дозволяє запускати цей процес вручну з вкладки Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Крок 1: Завантаження коду з вашого репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Крок 2: Налаштування середовища компілятора MSVC
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      # Крок 3: Компіляція проєкту за допомогою MSBuild
      - name: Build Solution
        working-directory: ./Source
        run: MSBuild.exe UACMe.sln /p:Configuration=Release /p:Platform=x64

      # Крок 4: Завантаження скомпільованого файлу як артефакту (ВИПРАВЛЕНО)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Akagi64-Executable
          path: Source/Akagi/output/x64/Release/akagi64.exe
